import {createHash} from 'node:crypto';
import {localize,localizedPath} from '../website/translations.mjs';
import {readFile,writeFile,cp,mkdir,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source=path.join(root,'website');const out=path.join(root,'build');
const versions={};for(const file of ['styles.css','preferences.js'])versions[file]=createHash('sha256').update(await readFile(path.join(source,file))).digest('hex').slice(0,12);
const versioned=html=>html.replaceAll(' ↗<',' <span class="link-arrow" aria-hidden="true">↗</span><').replaceAll('href="/styles.css"',`href="/styles.css?v=${versions['styles.css']}"`).replaceAll('src="/preferences.js"',`src="/preferences.js?v=${versions['preferences.js']}"`);
const cv=await readFile(path.join(source,'content/CV-Dmitrii-Proshutinskii-v6.md'),'utf8');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const inline=s=>esc(s).replace(/\[([^\]]+)\]\((https:\/\/[^)]+)\)/g,'<a href="$2">$1 ↗</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const section=name=>cv.split(`## ${name}\n`)[1]?.split('\n## ')[0]?.trim()??'';
const linkedin='https://www.linkedin.com/in/koptehe/';const github='https://github.com/DmitriiProshutinskii';
const notes=[['Recreating Telegram’s profile effect<br>with metaballs and Flutter ↗','https://koptehe.medium.com/recreating-the-telegram-profile-effect-using-metaballs-and-flutter-92aa128a0cf5'],['Moving the camera with a<br>rotated viewport in 2GIS MSDK ↗','https://koptehe.medium.com/moving-the-camera-with-a-rotated-viewport-in-2gis-msdk-73d85f0f2a5f'],['Soft Text Outline Algorithm ↗','https://koptehe.medium.com/soft-text-outline-algorithm-3216e43802ed']];
const nav=active=>`<a class="skip" href="#main">Skip to content</a><header class="nav"><a class="logo" href="/" aria-label="Dmitrii Proshutinskii home">DP /</a><a class="mono identity" href="/" ${active==='home'?'aria-current="page"':''}>01 / DMITRII PROSHUTINSKII</a><nav class="nav-links mono" aria-label="Main navigation"><a href="/experience/" ${active==='experience'?'aria-current="page"':''}>02 / EXPERIENCE</a><a href="/travels/" ${active==='travels'?'aria-current="page"':''}>03 / TRAVELS</a><a href="mailto:koptehe@gmail.com">LET’S TALK ↗</a></nav></header>`;
const socials=`<div class="row mono"><a href="${github}">GITHUB ↗</a><a href="${linkedin}">LINKEDIN ↗</a><a href="https://t.me/koptehe">TELEGRAM ↗</a></div>`;
const footer=(full=false)=>`<footer class="footer-wrap"><div class="section stack ${full?'contact':'simple-footer'}">${full?'<p class="mono">HAVE SOMETHING IN MIND?</p><div class="row spread"><h2>Let’s build it well.</h2><span class="contact-arrow" aria-hidden="true">↗</span></div><a class="title" href="mailto:koptehe@gmail.com">koptehe@gmail.com</a>':'<div class="row spread"><h2>Let’s talk.</h2><a href="mailto:koptehe@gmail.com">koptehe@gmail.com ↗</a></div>'}<hr class="divider"><div class="row spread footer-meta"><p class="mono">DMITRII PROSHUTINSKII / 2026</p>${socials}</div></div></footer>`;
const shell=(active,title,description,body)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f6f5f1"><link rel="canonical" href="https://proshutinskii.com/${active==='home'?'':active+'/'}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/inter-regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/styles.css"></head><body>${nav(active)}<main id="main">${body}</main>${footer(active==='home')}</body></html>`;
const home=`<section class="section stack home-intro"><div class="row spread mono"><p>INDEPENDENT MIND. PRODUCT ENGINEER.</p><p>TBILISI, GEORGIA / UTC +04</p></div><div class="hero-composition"><div class="stack hero-copy"><h1>Thoughtful apps.<br>Solid engineering.</h1><div class="title">Dmitrii Proshutinskii<br>Senior Mobile Engineer | Flutter / Dart</div><p class="muted">I turn complex ideas into mobile experiences that feel simple. From the first architectural decision to the details you touch.</p><div class="row"><a class="button" href="mailto:koptehe@gmail.com">START A CONVERSATION ↗</a><div class="stack compact mono"><a href="${github}">GITHUB ↗</a><a href="${linkedin}">LINKEDIN ↗</a></div></div></div><div class="portrait"><img src="/assets/portrait.png" alt="Dmitrii in a mountain landscape" width="941" height="1672" fetchpriority="high"></div></div><div class="proof border"><div><p class="metric">5+</p><p class="mono">YEARS IN MOBILE</p></div><div><p class="metric">3.5 → 2s</p><p class="mono">STARTUP TO USABLE HOME SCREEN</p><p class="small muted">Manual measurements · Balady</p></div><div><p class="metric">6 months</p><p class="mono">FIRST iOS + ANDROID RELEASES</p><p class="small muted">Sole mobile engineer · Epic Charging</p></div></div></section>
<section class="section stack work-section" aria-label="Selected experience"><div class="row spread"><p class="mono">02 / SELECTED EXPERIENCE</p><a class="mono" href="/experience/">FULL EXPERIENCE ↗</a></div><article class="feature panel"><div class="stack"><p class="mono">01 / URBI · USETECH / MAR 2024 — PRESENT</p><h2>Faster starts.<br>Smarter search.</h2><p class="muted">Balady — navigation and maps for Saudi Arabia. Reached 500,000 MAU in 2025 (internal analytics). I build native integrations and lead hands-on mobile engineering.</p><p class="mono">FLUTTER / ANDROID AUTO / APPLE CARPLAY</p><a class="mono" href="https://www.balady.gov.sa/ar">EXPLORE BALADY ↗</a></div><div class="stack report border"><p class="mono">SEARCH / INPUT-TO-RESULTS LATENCY</p><p class="metric">−10–15%</p><p class="small muted">Approximate latency reduction over six months. Manual measurements.</p><hr class="divider"><p class="mono">BEFORE / RELATIVE LATENCY</p><div class="bar" aria-hidden="true"></div><p class="mono">AFTER / QUERY-AWARE CACHING</p><div class="bar after" aria-hidden="true"></div><p class="small muted">Eliminated unnecessary requests and implemented query-aware caching.</p></div></article><article class="feature border"><div class="stack compact"><p class="mono">02 / EPIC CHARGING / 2023 — 2024</p><h3>From architecture to the App Store.</h3><p class="muted">Sole mobile engineer for the first releases: architecture, features, testing and store submission. Reworked an existing Flutter codebase while continuing delivery.</p></div><div class="stack compact"><h3>Shipped in 6 months</h3><p class="small muted">First iOS and Android releases to the App Store and Google Play.</p><a class="mono" href="https://epiccharging.com/">EXPLORE EPIC CHARGING ↗</a></div></article><hr class="divider"></section>
<div class="full-dark"><section class="section stack projects dark"><h2>Small tools. Real life.</h2><p>Products I build around everyday problems.</p><div class="cards">${[['[01] / REFLECTION','KBT Note','A quiet space to capture automatic thoughts before they slip away.','iOS','https://apps.apple.com/ru/app/kbt-note/id6747595502','RuStore','https://www.rustore.ru/catalog/app/com.koptehe.kbtnote'],['[02] / OFFLINE FIRST','Life Tracker','Journal, expenses, tasks and habits. One local timeline. No account, no server.','iOS','https://apps.apple.com/vn/app/life-tracker-journal-budget/id6759490732'],['[03] / EARLY ADOPTERS','RusCaps','Russian subtitles for short-form video, with careful line breaks and timing.','WEB SERVICE','https://app.ruscaps.tech/']].map(([idx,title,desc,label,url,label2,url2])=>`<article class="card stack"><p class="mono">${idx}</p><h3>${title}</h3><p>${desc}</p><div class="row mono"><a href="${url}">${label} ↗</a>${url2?`<a href="${url2}">${label2} ↗</a>`:''}</div></article>`).join('')}</div></section></div>
<section class="section about"><div class="stack"><h2>Care for the details.<br>Own the whole picture.</h2><p class="muted">I’ve worked across large engineering teams and early-stage startups — building architecture, shipping features and mentoring developers.</p><p class="small muted">Applied Mathematics &amp; Physics, MIPT<br>Bachelor’s and Master’s · 2014–2020</p><p class="mono">FLUTTER / DART / MOBILE ARCHITECTURE / TESTING</p></div><div class="stack writing"><p class="mono">FIELD NOTES / SELECTED WRITING</p><hr class="divider">${notes.map(([name,url])=>`<a href="${url}">${name}</a>`).join('')}</div></section>`;
const roles=section('Experience').split(/^### /m).filter(Boolean).map(block=>{const [heading,...rest]=block.trim().split('\n');const paragraphs=rest.join('\n').trim().split(/\n\s*\n/);const date=paragraphs.shift();const bullets=paragraphs.filter(x=>x.startsWith('- ')).flatMap(x=>x.split('\n').filter(y=>y.startsWith('- ')).map(x=>x.slice(2)));const desc=paragraphs.filter(x=>!x.startsWith('- '));return {heading,date,bullets,desc};});
const skills=section('Technical Skills').split(/\n\s*\n/).map(p=>`<p>${inline(p)}</p>`).join('');
const experience=`<section class="section stack experience-hero"><div class="row spread mono"><p>02 / EXPERIENCE</p><p>CURRICULUM VITAE / PROFILE</p></div><h1>Experience.</h1><div class="title">Dmitrii Proshutinskii<br>Senior Mobile Engineer | Flutter / Dart</div><p class="summary muted">${inline(section('Summary'))}</p><div class="row mono cv-contact"><a href="mailto:koptehe+job@gmail.com">KOPTEHE+JOB@GMAIL.COM ↗</a><a href="${linkedin}">LINKEDIN ↗</a><a href="${github}">GITHUB ↗</a><button class="button print-action" onclick="window.print()">PRINT / SAVE PDF ↗</button></div></section><div class="section cv-layout"><aside class="stack cv-sidebar"><section class="stack compact"><h2>PROFILE / LOCATION</h2><p class="title">Tbilisi, Georgia</p><p class="muted">Open to remote work and relocation to the EU / UAE.</p></section><section class="stack compact"><h2>TECHNICAL SKILLS</h2>${skills}</section><section class="stack compact"><h2>EDUCATION</h2><p class="title">Moscow Institute of Physics and Technology</p><p class="muted">Bachelor of Science and Master of Science<br>Applied Mathematics and Physics<br>2014–2020</p></section><section class="stack compact"><h2>LANGUAGES</h2><p>Russian — native<br>English — professional working proficiency<br>Spanish — A2, DELE certificate</p></section><section class="stack compact"><h2>TECHNICAL WRITING</h2>${notes.slice(0,2).map(([name,url])=>`<p><a href="${url}">${name.replaceAll('<br>',' ')}</a></p>`).join('')}</section></aside><div class="stack cv-main"><p class="mono">PROFESSIONAL EXPERIENCE / 2017 — PRESENT</p>${roles.map((r,i)=>`<article class="stack role ${i===0?'featured':''}"><p class="mono">${inline(r.date)}</p><h2>${esc(r.heading.split(' — ')[0])}</h2><p class="title">${esc(r.heading.split(' — ')[1])}</p>${r.desc.map(d=>`<p class="muted">${inline(d)}</p>`).join('')}<ul>${r.bullets.map(b=>`<li>${inline(b)}</li>`).join('')}</ul></article>`).join('')}<section class="stack cv-project"><h2>SELECTED PROJECTS</h2>${section('Selected Projects').split('\n').filter(x=>x.startsWith('- ')).map(p=>`<p>${inline(p.slice(2))}</p>`).join('')}</section></div></div>`;
const trips=[['georgia','Georgia','OCTOBER 2026','Vardzia & Akhaltsikhe.','A mini-trip through Georgia in October 2026: Vardzia, Akhaltsikhe and the road between.',['VARDZIA','A VIEW FROM THE CAVE','ON THE ROAD']],['kamchatka','Kamchatka','AUGUST','Volcanoes, ocean, open space.','An August trip to Kamchatka. A short visual chapter devoted to its volcanic landscape and Pacific coastline.',['VOLCANIC LANDSCAPE','ON THE TRAIL','A BEAR BY THE WATER']],['vietnam','Vietnam','MAY–JUNE','A different rhythm.','Vietnam was part of my May–June travels. A few frames to hold the contrast between streets, water and tropical scenery.',['LIMESTONE & WATER','STREET TEXTURES','ALONG THE COAST']],['china','China','MAY–JUNE','Between scales.','Another chapter from May–June: China. An image study moving between landscapes, architectural details and the scale of a city.',['LANDSCAPE','ARCHITECTURAL DETAILS','CITY SCALE']],['singapore','Singapore','MAY–JUNE','City meets green.','Singapore, during the same May–June stretch. A compact visual note on the city, its greenery and its layers of architecture.',['WATERFRONT','URBAN GREENERY','HERITAGE FACADES']]];
// Personal photographs use normal image fills; concept illustrations retain the original atlas columns.
const photos={georgia:[['georgia-vardzia',2000,1500,'Vardzia’s cave monastery and valley'],['georgia-cave',1050,1400,'View of the valley from a cave in Vardzia'],['georgia-road',918,1200,'A winding road through Georgia']],kamchatka:[['kamchatka-volcano',1200,1600,'A volcano rising above clouds in Kamchatka'],['kamchatka-hike',1050,1400,'Dmitrii hiking among rocks and steam in Kamchatka'],['kamchatka-bear',1400,787,'A brown bear beside the water in Kamchatka']]};
const atlasColumns={vietnam:1,china:2,singapore:3};
const gallery=trip=>`<div class="gallery">${trip[5].map((caption,row)=>{const photo=photos[trip[0]]?.[row];return `<figure><div class="photo-viewport"><div class="photo ${photo?'actual-photo': ''}" ${photo?'':`data-col="${atlasColumns[trip[0]]}" data-row="${row}"`}><img src="${photo?'/assets/travel/'+photo[0]+'.jpg':'/assets/travel-atlas.png'}" alt="${photo?photo[3]:`AI-generated destination illustration: ${trip[1]}, ${caption.toLowerCase()}`}" loading="lazy" width="${photo?photo[1]:1536}" height="${photo?photo[2]:1024}"></div></div><figcaption class="mono">[0${row+1}] ${caption}</figcaption></figure>`}).join('')}</div>`;
const travels=`<section class="travel-hero real-hero"><img src="/assets/travel/georgia-vardzia.jpg" alt="Vardzia’s cave monastery and valley" width="2000" height="1500" fetchpriority="high"><div class="shade"></div><div class="stack travel-hero-copy"><p class="mono">03 / TRAVELS · PERSONAL FIELD NOTES</p><h1>Away from<br>the screen.</h1><p>Places I’ve been. A few frames to keep.</p></div><div class="row spread mono travel-hero-meta"><p>GEORGIA / OCTOBER 2026</p><a href="#journal">SCROLL TO THE JOURNAL ↓</a></div></section><section class="section stack travel-intro" id="journal"><div class="travel-intro-grid"><h2>A few places.<br>A different pace.</h2><div class="stack compact"><p class="mono">OCTOBER 2026 / AUGUST / MAY–JUNE</p><p class="muted">A personal travel journal, in short entries: where I went, a little context and a few images.</p><p class="mono">5 PLACES / 15 FRAMES</p></div></div><nav class="trip-index mono" aria-label="Travel destinations">${trips.map((t,i)=>`<a href="#${t[0]}">0${i+1} / ${t[1].toUpperCase()}</a>`).join('')}</nav></section>${trips.map((t,i)=>`<div class="${i%2===1?'panel':''}"><section class="section stack trip" id="${t[0]}"><div class="trip-header"><div class="stack compact"><p class="mono">0${i+1} / ${t[2]}</p><h2>${t[1]}</h2></div><div class="stack compact"><h3>${t[3]}</h3><p class="muted">${t[4]}</p></div></div>${gallery(t)}<p class="mono muted trip-note">${photos[t[0]]?'PERSONAL PHOTOGRAPHS':'DESTINATION STUDY / AI-GENERATED IMAGES'}</p></section></div>`).join('')}<div class="full-dark"><section class="section travel-outro dark"><h2>More to see.<br>More to keep.</h2><div class="stack compact"><p class="mono">ABOUT THE IMAGES</p><p>Georgia and Kamchatka feature my own photographs. The images for Vietnam, China and Singapore are AI-generated illustrations from the original design concept.</p></div></section></div><script src="/travel-images.js" defer></script>`;
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(path.join(source,'assets'),path.join(out,'assets'),{recursive:true});await cp(path.join(source,'styles.css'),path.join(out,'styles.css'));await cp(path.join(source,'travel-images.js'),path.join(out,'travel-images.js'));await cp(path.join(source,'preferences.js'),path.join(out,'preferences.js'));
for(const [route,html] of [['',shell('home','Dmitrii Proshutinskii — Senior Mobile Engineer','Flutter / Dart engineer building thoughtful mobile apps. Architecture, performance, native integrations and independent products.',home)],['experience',shell('experience','Experience — Dmitrii Proshutinskii','Professional experience, engineering outcomes, technical skills and education. Senior Mobile Engineer | Flutter / Dart.',experience)],['travels',shell('travels','Travels — Dmitrii Proshutinskii','Personal travel notes from Georgia, Kamchatka, Vietnam, China and Singapore.',travels)]]){for(const lang of ['en','ru','es']){const active=route||'home';const dir=path.join(out,localizedPath(active,lang));await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),versioned(localize(html,lang,active)));}}
await cp(path.join(root,'CNAME'),path.join(out,'CNAME'));await writeFile(path.join(out,'.nojekyll'),'');await writeFile(path.join(out,'404.html'),localize(shell('home','Page not found — Dmitrii Proshutinskii','Page not found.',`<section class="section stack not-found"><p class="mono">404 / PAGE NOT FOUND</p><h1>A different path.</h1><p>The page you’re looking for isn’t here.</p><a class="button" href="/">BACK TO HOME ↗</a></section>`),'en','home'));
// Preserve previously shared resume URLs while the portfolio evolves.
for(const oldRoute of ['resume','about','projects','contact','stats']){await mkdir(path.join(out,oldRoute),{recursive:true});const target=oldRoute==='resume'?'/experience/':'/';await writeFile(path.join(out,oldRoute,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${target}"><title>Moved — Dmitrii Proshutinskii</title><link rel="canonical" href="https://proshutinskii.com${target}"></head><body><a href="${target}">Continue to the portfolio</a></body></html>`);}
await cp(path.join(root,'Proshutinskii_Flutter_developer.pdf'),path.join(out,'Proshutinskii_Flutter_developer.pdf'));
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://proshutinskii.com/sitemap.xml\n');await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['en','ru','es'].flatMap(lang=>['home','experience','travels'].map(route=>`<url><loc>https://proshutinskii.com${localizedPath(route,lang)}</loc></url>`)).join('')}</urlset>`);
console.log('Built home, experience and travels → build/');
